#!/bin/sh
# Main trigger file. (That bin/sh string is there just to fool some editors to use bash colorization)
# 
# [X <ext>] means: X [L level] [A "action"] [W] [M missing_chars] [S] [C]
# If there's no X around there, it won't look for those extended options.
# 
# "message" affliction give/cure [X <ext>]
#           special part body/leftarm/etc healed/crippled/mangled/mangled2 [X <ext>]
#           special <trip/instakill/ignorenext> [X <ext>]
#           special defence defencename give/take [X <ext>]
#
# A "afflictionname" herb smoke salve focus purge special ["diag message"]
# D defence "defencename" [X <ext>]
#
# Level 1: Safe triggers.
# Level 2: Dangerous triggers.
# Level 3: Afflictions.


# Cure Table.

# C "curename" "command" type ["plant name"]
# Command is irrelevant for types other than 'none'.
# Plant name is irrelevant for types other than 'herb'.

# Name         Command             Type      Plant
C wormwood     "eat wormwood"      herb      "a wormwood root"
C mandrake     "eat mandrake"      herb      "a mandrake root"
C orphine      "eat orphine"       herb      "an orphine seed"
C kelp         "eat kelp"          herb      "a piece of kelp"
C nightshade   "eat nightshade"    herb      "a nightshade root"
C galingale    "eat galingale"     herb      "a galingale flower"
C maidenhair   "eat maidenhair"    herb      "a maidenhair leaf"
C epidermal    "apply epidermal"   salve
C caloric      "apply caloric"     salve
C mending      "apply mending"     salve
C restoration  "apply restoration" salve
C lovage       "smokelovage"       smoke
C laurel       "smokelaurel"       smoke
C immunity     "drink immunity"    none
C compose      "compose"           none
C concentrate  "concentrate"       none
C sight        "sight"             none
C hearing      "hearing"           none
C fitness      "fitness"           none



# Affliction Table.

# Name                  Herb, smoke, salve     Fcs Prg  Special      Diagnosis
#  Herbs.
A "madness"             n/a laurel n/a         no  no   n/a          "hearing whispers of madness."
A "stupidity"           orphine n/a n/a        yes no   n/a          "unnaturally stupid."
A "hellsight"           n/a laurel n/a         no  no   n/a          "catching glimpses of Hell."
A "hypochondria"        kelp n/a n/a           no  no   n/a          "a certified hypochondriac."
A "anorexia"            n/a n/a epidermal      yes no   n/a          "anorexic."
A "asthma"              kelp n/a n/a           no  yes  fitness      "afflicted by horrible asthma."
A "slickness"           maidenhair lovage n/a  no  no   n/a          "extremely oily."
A "fear"                n/a n/a n/a            no  no   compose      "afflicted by fear."
A "dissonance"          mandrake n/a n/a       no  no   n/a          "has a dissonant nature."
A "equilloss"           n/a n/a n/a            no  no   concentrate  "---"
A "mana-leech"          n/a lovage n/a         no  no   n/a          "a victim of manaleech."
A "recklessness"        mandrake n/a n/a       no  no   n/a          "reckless."
A "herbs-reject"        nightshade n/a n/a     no  no   n/a          "unable to digest herbs properly."
A "sunlight-allergy"    nightshade n/a n/a     no  no   n/a          "allergic to sunlight."
A "paralysis"           maidenhair n/a n/a     no  yes  n/a          "paralysed."
A "clumsiness"          kelp n/a n/a           no  yes  n/a          "afflicted with clumsiness."
A "left-leg-paralysis"  maidenhair n/a n/a     no  no   n/a          "has a paralysed left leg."
A "right-leg-paralysis" maidenhair n/a n/a     no  no   n/a          "has a paralysed right leg."
A "left-arm-paralysis"  maidenhair n/a n/a     no  no   n/a          "has a paralysed left arm."
A "right-arm-paralysis" maidenhair n/a n/a     no  no   n/a          "has a paralysed right arm."
A "cyanide"             n/a n/a n/a            no  yes  immunity     "suffering from cyanide."
A "weakness"            kelp n/a n/a           yes yes  n/a          "wearied in body."
A "sensitivity"         maidenhair n/a n/a     no  yes  n/a          "sensitive to pain."
A "salves-slow"         kelp n/a n/a           no  no   n/a          "afflicted with poor salve absorption."
A "generosity"          galingale n/a n/a      no  no   n/a
A "confusion"           wormwood n/a n/a       no  no   n/a          "confused."
A "haemophilia"         nightshade n/a n/a     no  no   n/a          "afflicted by thin blood."
A "health-leech"        kelp n/a n/a           no  no   n/a          "a victim of healthleech."
A "hypersomnia"         wormwood n/a n/a       no  no   n/a          "hypersomnic."
A "masochism"           orphine n/a n/a        yes no   n/a          "masochistic."
A "dizziness"           mandrake n/a n/a       yes no   n/a          "overcome by dizziness."
A "peace"               galingale n/a n/a      no  no   n/a          "feeling unnaturally tranquil."
A "pacifism"            galingale n/a n/a      no  no   n/a          "pacified."
A "hallucinations"      wormwood n/a n/a       no  no   n/a          "hallucinating."
A "impatience"          mandrake n/a n/a       no  no   n/a          "impatient."
A "paranoia"            wormwood n/a n/a       no  no   n/a          "paranoid."
A "justice"             galingale n/a n/a      no  no   n/a          "surrounded by the aura of justice."
A "lovers"              galingale n/a n/a      no  no   n/a          "Desperately in love with *."
A "dementia"            wormwood n/a n/a       no  no   n/a          "demented."
A "claustrophobia"      orphine n/a n/a        yes no   n/a          "claustrophobic."
A "agoraphobia"         orphine n/a n/a        no  no   n/a
A "vertigo"             orphine n/a n/a        yes no   n/a          "afraid of heights."
A "shyness"             mandrake n/a n/a       yes no   n/a          "afflicted by unbearable shyness."
A "nausea"              nightshade n/a n/a     no  yes  n/a          "violently ill."
A "deadening"           mandrake n/a n/a       no  no   n/a          "of a deadened mind."
A "lethargy"            nightshade n/a n/a     no  no   n/a          "feeling rather lethargic."
#  Unknown.
A "addiction"           nightshade n/a n/a     no  no   n/a
A "larkspur"            mandrake n/a n/a       no  no   n/a
A "berserking"          orphine n/a n/a        no  no   n/a
A "loneliness"          orphine n/a n/a        no  no   n/a          "very lonely."
A "scytherus"           nightshade n/a n/a     no  no   n/a
#  Salves.
A "herbs-slow"          n/a n/a epidermal      no  no   n/a          "afflicted with slow herb digestion."
A "freezing"            n/a n/a caloric        no  no   n/a          "frozen stiff."
A "chills"              n/a n/a caloric        no  no   n/a          "shivering."
A "elixirs-slow"        n/a n/a epidermal      no  no   n/a          "unable to process healing elixirs efficiently."
A "fire"                n/a n/a mending        no  no   n/a          "ablaze."
A "withered-throat"     n/a n/a epidermal      no  no   n/a          "stricken with a withered throat."
#  Unknown.
A "stuttering"          n/a n/a epidermal      no  no   n/a
#  Pipes.
A "equilibrium-slow"    n/a laurel n/a         no  no   n/a          "unable to regain equilibrium quickly."
A "balance-slow"        n/a lovage n/a         no  no   n/a          "unable to regain balance quickly."
A "epilepsy"            n/a laurel n/a         yes no   n/a          "suffering from epilepsy."
A "scars"               n/a n/a mending        no  no   n/a          "horribly scarred."
A "disfigurement"       n/a n/a epidermal      no  no   n/a          "disfigured beyond recognition."
A "disloyalty"          n/a lovage n/a         no  no   n/a          "inspiring disloyalty in those nearby."
#  Unknown.
A "curse"               n/a laurel n/a         no  no   n/a
 
#  Misc.
A "blackout"            n/a n/a n/a            no  no   n/a          "devoid of senses."
A "rune-restoration"    n/a n/a restoration    no  no   n/a
A "rune-mending"        n/a n/a epidermal      no  no   n/a

# An unknown affliction, but we know we have at least one.
A "something"           n/a n/a n/a            no  no   n/a          "---"



# Affliction give/cure messages.

# Hallucinations.
"Spiders are erupting from your mouth and nose!" hallucinations give
"Ooh look! A lovely lake. Perhaps you'll dive in!" hallucinations give
"An unseen being takes you to one side and whispers conspiratorially to you." hallucinations give
"You are stunned by the sight of a massive pink bunny hopping by." hallucinations give
"You are stunned by a vision of the Creator." hallucinations give
"*and your mind expands with alien and strange visions." hallucinations give
"Your vision blurs for a moment." hallucinations give
"Your hallucinations cease to plague you." hallucinations cure

# Confusion.
"Your head spins as your mind is drowned in chaos and confusion." confusion give
"You reel as the beam strikes, dazzled and confused." confusion give
"You are too confused to concentrate properly" confusion give
"The bubonis entity strokes your forehead and your thoughts are thrown into*" confusion give
"*but the purpose of doing so eludes you." confusion give
"The kick connects, and all rational thought flies from your head as you swoon*" confusion give
"You are too confused to concentrate on anything." confusion give
"^ spins about you, flashing his shield into your eyes confusing you." confusion give
"You raise your weapons to strike, but the purpose for it eludes you." confusion give
"The confusion lifts from your mind and it is clear once again." confusion cure
#sab:
"Your mind feels suddenly confused and jumbled." confusion give

# Recklessness.
"None may stand in your way! You are invincible!" recklessness give
"Pain leaves your body and you feel ready to take on the world." recklessness give
"Pain is something only the weak feel!" recklessness give
"You grit your teeth, resolving to battle on through the mightiest blows*" recklessness give
"Your heroic actions can no longer go unnoticed*" recklessness give
"The disciplined melody of the Battlemarch prevents you from rushing into battle*" recklessness cure
"Prudence rules your psyche once again." recklessness cure

# Shyness.
"You suddenly begin feeling nervous." shyness give
"Sudden, irrational fear fills your mind." shyness give
"Unable to bear the company of others, you depart in terror." shyness give
"Heart thumping, you cannot bear the company of others and depart*" shyness give
"The bubonis entity cuts you slightly, and you become unbearably shy*" shyness give
"You can now face the world boldly, shy no more." shyness cure

# Clumsiness.
"You stumble and it becomes very difficult to concentrate on your coordination." clumsiness give
#sab:
"A strange feeling overtakes you." clumsiness give
"You lash out clumsily*" clumsiness give
"You feel coordinated once more." clumsiness cure

# Asthma.
"Your lungs tighten and it becomes hard to breathe." asthma give
"Your heavy lungs are much too constricted to smoke*" asthma give
"There is a tightening sensation in your lungs*" asthma give
"Your lungs relax and you can breath easy once again." asthma cure
"You inhale deeply, allowing the air to fill your mighty lungs." asthma cure X S
"You purge yourself of the affliction of constriction." asthma cure

# Stupidity.
"You suddenly find it hard to finish thinking of..." stupidity give
"Hmmmm. Why must everything be so difficult to figure out?" stupidity give
"Your thoughts become jumbled and you have trouble thinking." stupidity give
"Strange, everything doesn't quite seem so simple anymore." stupidity give
"All this thinking is beginning to hurt." stupidity give
"Your mind becomes foggy and you are unable to think clearly." stupidity give
"You are unable to think properly." stupidity give
"* casts a net of stupidity over your mind." stupidity give
"* glares at you and a feeling of utter stupidity envelops you." stupidity give
"Your mind feels somewhat slower and more plodding." stupidity give
"A bulky, snarling orc uses his massive fist to deliver a stunning *" stupidity give
"A large spider moves quickly forward and bites you. The searing pain of the*" stupidity give
"Sharp claws spring out from within a marauders camouflage, slashing you*" stupidity give
"A demon resembling a wailing banshee focuses his gaze upon you. He suddenly *" stupidity give
"A large armoured orc uses his massive fist to deliver a stunning blow to the*" stupidity give
"Ahh, you feel able to reason once more." stupidity cure

# Paralysis.  We have a special one here.
"Your body stiffens rapidly with paralysis." paralysis give
"You feel your limbs stiffen and lock up in response to an unseen power." paralysis give
"Terror takes hold, as a numb sensation overcomes your body." paralysis give X M 3
"The bees sting you into paralysis." paralysis give
"*your muscles stiffen and lock as a ghast brushes you with a finger." paralysis give
"Your muscles stiffen and lock as a vampire gazes at you hypnotically." paralysis give
"respond go your commands." paralysis give
"The Song of Bedazzlement writhes in front of your eyes." paralysis give
"*struck by lightning, causing your limbs to freeze." paralysis give
"Your limbs lock up in paralysis as you see an inguz rune on a totem." paralysis give
"Pain races across the back of your neck and your limbs freeze up." paralysis give
"A large spider moves quickly forward and bites you. The searing pain of the*" paralysis give
"Sharp claws spring out from within a marauders camouflage, slashing you*" paralysis give
"A wailing banshee focuses her gaze upon you. She suddenly screams in a high*" paralysis give 
"A demon resembling a wailing banshee focuses his gaze upon you. He suddenly *" paralysis give
"Your paralysis fades and you can move once more." paralysis cure
# Already.
"Frustratingly, your body won't respond to your call to action." paralysis give
"Paralysed as you are, your body is not able to pick up anything." paralysis give
"You are afflicted with paralysis and cannot do that." paralysis give
"Your muscles cry out in agony as you try to call them to action." paralysis give
"Your muscles are paralysed and hence you cannot do that." paralysis give
"You are paralysed and unable to do that." paralysis give
"The paralysis of your muscles prevents you from doing that." paralysis give

# Anorexia.
"The idea of eating or drinking is repulsive to you." anorexia give
"You feel suddenly as if food is the most repulsive thing you can imagine." anorexia give
"The thought of food revolts you all of a sudden*" anorexia give
"The thought of eating sickens you." anorexia give
"Food is no longer repulsive to you." anorexia cure

# Generosity.
"Why, you ask yourself, are you so privileged when others are so needy." generosity give
"Your boundless generosity shines through once more!" generosity give
"Ahhhh. The freedom to be stingy again!" generosity cure

# Dementia.
"You look about yourself, frenzied and wild-eyed." dementia give
"Sanity returns to you and you are no longer demented." dementia cure

# Paranoia.
"Unthinking paranoia overcomes you." paranoia give
"Aaaahhh. No one is out to get you after all." paranoia cure

# Hypochondria.
"My, you feel healthier than you have in years." hypochondria cure


# Dizziness.
"Your mind swims as dizziness overtakes you." dizziness give
"You feel light headed and dizzy." dizziness give
"The ground seems to tilt and you fall with a thump." dizziness give
"Stability returns and you are no longer dizzy." dizziness cure

# Impatience.
"You shuffle your feet noisily, suddenly bored." impatience give
"You're unable to focus your mind." impatience give
"You are patient once again." impatience cure

# Deadening.
"You feel a deadening pall overcome your mind, put there by *" deadening give
"Your mind is no longer deadened." deadening cure

# Berserking (nothing)
# ...

# Claustrophobia.
"The walls close in to suffocate you - you must escape!" claustrophobia give
"You are gripped with fear as you face the threshold - you cannot go indoors!" claustrophobia give
"*, the bubonis entity whispers to you." claustrophobia give
"Small spaces no longer frighten you." claustrophobia cure

# Masochism.
"An odd sensation descends upon you." masochism give
"You use your right foot to stomp on your left as hard as possible." masochism give
"You drive a clenched fist into your gut." masochism give
"You feel the urge to slash, cut, and bruise yourself." masochism give
"With the heel of your palm, you smack yourself upside the head." masochism give
"You smile with pleasure as you ram your fist into your jaw." masochism give
"You no longer enjoy pain." masochism cure

# Agoraphobia.
"Terror descends upon you and your head swims - you must find shelter!" agoraphobia give
"You can handle the idea of open spaces again." agoraphobia cure

# Loneliness. (nothing)
# ...

# Vertigo.
"The thought of heights is more than you can bear." vertigo give
"The idea of heights makes you queasy suddenly." vertigo give
"You are gripped with fear - you cannot leave the ground." vertigo give
"You can control your fear of heights." vertigo cure

# Haemophilia.
"You swoon as you suffer a toxic relapse." haemophilia give X F
"You swoon as you suffer a toxin relapse.*" special ignorenext
"You feel your blood thickening." haemophilia cure

# Xeroderma, sunlight-allergy.
"Your skin tingles as the light grows in intensity, eventually growing into a " sunlight-allergy give
"The fierce sun ripples across your skin like the fury of Baar, Lord of*" sunlight-allergy give X F
"Your vision is flooded with light, and your face suddenly reddens." sunlight-allergy give
"You stagger, disoriented by the searing agony of the sunlight!" sunlight-allergy give
"Sunlight shines down upon you mercilessly*" sunlight-allergy give
"You feel your allergy to the sun going into temporary remission." sunlight-allergy give
"No longer will the sunlight harm you." sunlight-allergy cure

# Lethargy.
#sab:
"You feel your energy robbed from you as lethargy overtakes you." lethargy give
"The lethargy evaporates, leaving you full of energy." lethargy cure


# Eyphorbia. (nothing)
# ...

# Nausea.
"A sense of extreme nausea washes over you." nausea give
"You cannot contain the convulsions in your stomach any longer and double over,*" nausea give
"Your stomach becalms itself." nausea cure
"The venom forces you to gag slightly, but your superior constitution shrugs off" nausea cure

# Addiction.
"You feel a terrible thirst for elixirs grow within you." addiction give
"Your terrible addiction to lovely elixirs seems to wane." addiction cure

# Pacifism.
"A feeling of peace and well being overcomes you." pacifism give
"Your will to harm anything leaves you." pacifism give
"Your heart is filled with divine love, violence is abhorrent to you." pacifism give
"The unnatural feeling of peace leaves you." pacifism cure
#"gazes fondly at you, eyes shining"
"You are roused into anger." pacifism cure

# Peace. (tranquil)
"Your mind softens as you feel your entire being filled with a deep inner peace." peace give
"A sense of deep inner calm descends on you." peace give
"You are capable of offensive acts once more." peace cure
"The unnatural calm that filled you lifts abruptly from you." peace cure

# Lovers. A special one, here, might not be 3.
"You love ^ far too much to even THINK of hurting*" lovers give X M 3
"^ throws a Lovers tarot at you and as it strikes true, you fall*" lovers give
"You are taken by a sudden and overwhelming affection for*" lovers give
"You shake your head, wondering what you ever saw in*" lovers cure

# Slickness.
"A strange smelling substance begins to leak from your pores." slickness give
"The salve cannot absorb into your slimy skin." slickness give
"The bubonis entity secretes a foul, slick substance that covers you." slickness give
"Your pores cease secreting the oily substance." slickness cure

# Disfigurement.
"^ curses you with the visage of a rotting corpse." disfigurement give
"Your horribly disfigured body is restored." disfigurement cure

# Disloyalty.
"Your horribly disfigured body is restored." disloyalty give
"You feel your body weaken and regress to a more primitive state." disloyalty give
"You feel ugliness radiating from you." disloyalty give
"You stand in such dishonour that not even your loyal friends will help you." disloyalty give
"Your spirit writhes in torment as it achieves new depths of dishonour." disloyalty give
"Blood spews as ^ lacerates your face with ^ knife, scarring*" disloyalty give
"You no longer will inspire disloyalty among friends." disloyalty cure

# Scars.
"^ feints towards your legs, then quickly brings the sharpened*" scars give
"^ feints towards your legs, then quickly brings the sharpened*" disloyalty give
"The horrible scars on your face still leave you disgustingly disfigured." disloyalty give
"The terrible scars on your face fade away." scars cure

# Rune carvings.
"As ^ finishes carving the ^ rune into your flesh, the ink*" rune-restoration give
"As ^ finishes carving the ^ rune into your flesh, the ink*" rune-mending cure X S
"The gaping wound on your chest stops bleeding." rune-restoration cure
"The gaping wound on your chest stops bleeding." rune-mending give
"The wound on your chest closes up, leaving only a scar." rune-restoration cure X S
"The wound on your chest closes up, leaving only a scar." rune-mending cure

# Aeon.
"You move sluggishly into action." special slow
"You feel your passage through time slow." special aeon give
"^ draws back with a knowing smirk and utters some alien*" special aeon give
"*open palm, and blows it lightly at you." special aeon give
"The curse of the Aeon wears off and you return to the normal timestream." special aeon cure
"*your movement through the time stream is slowed." special aeon give
"The vermillion glow within his cowl glows brighter as of the Felreign snaps his" special aeon give
"his eyes flash with white fire and the world around seems to slow to a halt." special aeon give
"the Wise into you as the purple ink disappears." special aeon give
"A purple bolt of magickal force slams from a nearly perfect sketch*" special aeon give

# Hellsight.
"An unspeakable, horrific image rises from the bowels of hell to plague you." hellsight give
"^ gives you a vengeful stare, and dark images begin to whisper to you*" hellsight give
"Your mind is filled with horrifying visions of Hell." hellsight give
"Thankfully, the visions of Hell have left you." hellsight cure
"*the edges of your mind." hellsight give

# Curse. (nothing)
# ...

# Epilepsy.
"Your nerves feel suddenly jangled." epilepsy give
"Your limbs begin to jerk and shake uncontrollably, and you begin to foam at the" epilepsy give
"Sparks fly out at you from * and your nerves feel jangled." epilepsy give
"Your nerves suddenly calm down." epilepsy cure

# Sensitivity.
"A prickly, stinging sensation spreads through your body." sensitivity give
"The stinging feeling fades." sensitivity cure

# Weakness.
"Your limbs grow heavy and you groan feebly as weakness overcomes your body." weakness give
"You feel strength return to your limbs." weakness cure

# Dissonance. (no cure)
#"Your body is wracked with pain by the dissonant vibrations." dissonance give
#"You feel your body begin to vibrate in tune with the disruptive harmonies." dissonance give
"Your dissonant nature becomes harmonious." dissonance cure

# Justice. (nothing)
"Justice is dealt out and your attack rebounds onto you." justice give
"A set of scales appears above your head and one side of the scale quickly*" justice give
"The curse of Vahin, the Protector leaves you." justice cure
"The curse of justice leaves you." justice cure

# Cyanide.
"You begin feeling slightly flushed." cyanide give
"Blood begins to slowly drip from your nose." cyanide give
"You cough suddenly, expelling black fluid with bits of what looks to be tissue*" cyanide give
"Your legs tremble slightly as a yellow jaundice begins to creep through your*" cyanide give
"The dark void of terror fills your mind as, horribly, blood begins to seep out*" cyanide give
"A viper-like sleizak rune suddenly extends from a totem to bite you painfully." cyanide give
"A nearly perfect sketch of a female drelith darts forward at you suddenly*" cyanide give
"The venom burns through your veins, destroying the deadly poisons that are*" cyanide cure
"You purge the deadly poisons that are killing you from your veins." cyanide cure



# Chills.
"You feel the strength ebb from your body as the cold takes its toll." chills give
"*you, sending a strange chill deep into your bones." chills give
"* sends the cold of the grave to freeze you." chills give
"You suddenly have an extremely intense shiver." chills give
"Your body warms up and you stop shivering." chills cure
"A feeling of comfortable warmth spreads over you." chills cure X S
"You concentrate for a moment and a feeling of comfortable warmth fills you." chills cure X S
"Though still shivering, you are no longer gripped in icy paralysis." chills give X S
#"A feeling of comfortable warmth spreads over you."
#"blasts you with cold, frigid air"
#"blows a chill breath at you"
#"exhales a blast of frigidly cold air on you"
#"gestures grandly, and causes a deepfreeze to settle over"
#"raises a hand towards you and blasts you with cold"

# Frozen.
"As *a curved sabre* hits you, a numbing cold spreads through your body." freezing give
"Though still shivering, you are no longer gripped in icy paralysis." freezing cure
"Your body slows as it freezes in the extreme cold." freezing give
"A feeling of comfortable warmth spreads over you." freezing cure X S
"You concentrate for a moment and a feeling of comfortable warmth fills you." freezing cure X S

# Blindness.
# "For a moment you can see, then instantly, all is darkness." blindness give
# "The blow smashes into the bridge of your nose and your vision spins." blindness give
# "You can see once more." blindness cure
# "With a final blink your vision returns to you." blindness cure

# Fear.  We can compose safely, no illusion problems.
"Panic overcomes you as you rush about in circles." fear give X L 1 A "compose"
"A wave of utter panic washes over you." fear give X L 1 A "compose"
"You cry out as your mind is filled with abject terror! " fear give X L 1 A "compose"
"Throwing back ^ head, * lets out an eerie wail." fear give
"You begin to panic as you see a kena rune on a totem." fear give X L 1 A "compose"
"There is nothing to fear but fear itself." fear cure X F

# Hypersomnia.
"An urge to visit the Goddess of Dreams overcomes you*" hypersomnia give
"Your hypersomnia prevents your insomnia." hypersomnia give
"You feel a bit more alert and awake." hypersomnia cure

# Whispering Madness.
"^ passes his hand in front of you. You feel an invisible claw brush*" madness give
"You hear an eerie voice whisper horrible words in the back of your skull." madness give
"The whispering in your mind subsides." madness cure
"of your skull, but quickly brush it off." madness cure

# Mana-leech
"Your mana begins to drain away." mana-leech give
"Your rapidly weakening mind is stabilized." mana-leech cure

# Health-leech
"Your health begins to drain away." health-leech give
"Your aching, pain-wracked body is soothed and calmed." health-leech cure

# Fire.
"Flames erupt over all over your body and begin to consume your flesh." fire give
"Flames lick around you - you are on fire!" fire give
"You scream in agony as the horrific flames crackle over your melting flesh." fire give
"The unrelenting sunlight painfully sears your flesh, which spontaneously bursts*" fire give
"You are scorched by the firewall as you pass through." fire give
"A fiery efreeti spins into you, causing you to burst into flame*" fire give
"Extreme heat roars through your body at the touch*" fire give
"The cool waters quench the flames about your body." fire cure
"The raging fire about your skin is put out." fire cure

# Equilibrium loss.  We can also auto concentrate, no illusion problems.
"You feel ^'s mind attacking yours from all sides, and you lose your mental*" equilloss give X L 1 A "concentrate"
"You suddenly have an extremely intense shiver." equilloss give X L 1 A "concentrate"
"*concentrate before the flashing weapon." equilloss give X L 1 A "concentrate"
"Your equilibrium is disrupted by a high-pitched keening." equilloss give X L 1 A "concentrate"
"Your equilibrium is further disrupted by a high-pitched keening." equilloss give X L 1 A "concentrate"
"You are too confused to concentrate on anything." equilloss give
#"The unearthly screeching of the bloodworms disrupt your concentration." equilloss give X L 1 A "concentrate"
"^ whips ^ blade about ^ body and you find yourself unable to*" equilloss give X L 1 A "concentrate"
"You begin intense concentration to restore your equilibrium." equilloss cure
"You already possess mental equilibrium." equilloss cure

# Blackout.
"on a hard root, blacking your vision for a moment." blackout give X S
"screams in a high pitched voice causing a sonic wave to slam into you." blackout give X S
"Of the Felreign raises his arms high above his head, and the vermillion glow*" blackout give X S
"A nearly perfect sketch of a female drelith whips its tail around, striking you" blackout give X S
"slams you into the tunnel wall, the pain and overpowering stench causing you to" blackout give X S
"A devastating blast of telepathic energy strikes you and your senses black out*" blackout give X S
"You feel something akin to a veil passing over your senses." blackout give X S
"A female drelith whips its tail around, striking you in the head and knocking*" blackout give X S
"A demon resembling a wailing banshee focuses his gaze upon you. He suddenly *" blackout give X S
"Your senses return to you as the blackout ends." blackout cure X S
"Your senses return in a rush." blackout cure


# Trips.  Sweepkick, dropkick, and anything that makes you sit.
"^ knocks your legs out from under you and sends you sprawling to*" special trip
"*'s tail strikes your legs and sends you crashing to the ground." special trip
"The ground heaves and you are knocked to the ground." special trip
"* tearing at you with teeth and claws." special trip
"^ steps into the attack, grabs your arm, and throws you violently*" special trip
"sprawling to the desert sands." special trip
"The lion head on the chimera roars at you, stunning you with its power." special trip
"You leap up and attempt a graceful swan dive...right into the solid ground." special trip
"*he/she* slams into you, knocking you off your feet and stunning you!" special trip
"knocking you to the ground." special trip
"grip as it trips you, causing you to fall into the watery muck." special trip
"The wave of force knocks you to the ground." special trip
"Blue light crackles forth from ^'s palms, striking you down*" special trip
"causing massive rocks and boulders to fall down on you." special trip
"With incredible skill you tumble the ground, taking no damage." special trip
"causing tremors over the ground." special trip
"knocking the wind out of you and sending you sprawling." special trip
"in the head and knocking you to the ground." special trip
"You must stand up to do that." special trip

# Paralsysed limbs. Ugh, I hate the new code...
"A numbness seizes you, and your left leg goes limp." left-leg-paralysis give
"A numbness seizes you, and your right leg goes limp." right-leg-paralysis give
"A numbness seizes you, and your left arm goes limp." left-arm-paralysis give
"A numbness seizes you, and your right arm goes limp." right-arm-paralysis give
"You feel a tingling sensation run through your left leg as the paralysis*" left-leg-paralysis cure
"You feel a tingling sensation run through your right leg as the paralysis*" right-leg-paralysis cure
"You feel a tingling sensation run through your left arm as the paralysis*" left-arm-paralysis cure
"You feel a tingling sensation run through your right arm as the paralysis*" right-arm-paralysis cure
"The bubonis entity envelops your left leg and it goes limp." left-leg-paralysis give
"The bubonis entity envelops your right leg and it goes limp." right-leg-paralysis give
"The bubonis entity envelops your left arm and it goes limp." left-arm-paralysis give
"The bubonis entity envelops your right arm and it goes limp." right-arm-paralysis give

# Sleep.
"You feel incredibly tired, and fall asleep immediately." none X A "wake"


# Writhe.

# Webs.
"You have writhed free of your entanglement by webs." special writhe webs cure
"*webbing, which quickly entangles your limbs." special writhe webs give
"*rendering you helpless." special writhe webs give
"*webbing at you, entrapping you within its web." special writhe webs give
"Sticky strands of webbing prevent you from moving." special writhe webs give
"mass of azure energy streams out from ^ palm and binds you." special writhe webs give
"Sticky strands of webbing cling to you, making that impossible." special writhe webs give
"*you in a sticky webbing." special writhe webs give
"*encasing you in a sticky webbing." special writhe webs give
"*vomit of decaying fish over you." special writhe webs give
"A hopping poppy jumps at you aggressively, wrapping its long trailing roots*" special writhe webs give
"A large spider quickly and nimbly moves around you, encasing you in a sticky*" special writhe webs give
"A fearsome alligator suddenly clamps its vice-like jaws around your abdomen*" special writhe webs give

# Transfixed.
"You begin trying to wrest your mind free of that which has transfixed it." special writhe transfix begin
"You have writhed free of your state of transfixation." special writhe transfix cure
"With blinding speed, ^ transfixes you with a swirling pattern of fire*" special writhe transfix give
"*weaves an intricate dance, transfixing you." special writhe transfix give
"Your attention is grabbed and held by a fascinating butterfly-like rune." special writhe transfix give
"You are transfixed and cannot do that. You must writhe to escape." special writhe transfix give
"*your mind is transfixed." special writhe transfix give
"Flying in front of your face and around your head, a tiny cactus*" special writhe transfix give
"You are transfixed and cannot move." special writhe transfix give
"With blinding speed, an ogre warmage transfixes you with a swirling pattern of*" special writhe transfix give

# Impaled.
"You begin to writhe furiously to escape the blade that has impaled you." special writhe impale begin
"With an heroic effort you manage to writhe yourself free from the weapon*" special writhe impale cure
"* thrusts the weapon deep into your gut, impaling you." special writhe impale give
"^ draws his blade back and plunges it deep into your helpless body*" special writhe impale give
"Your health continues to drain away as your impale body shudders on the *" special writhe impale give
"The daegger has looped around and dives toward your shadow, impaling it and*" special writhe impale give
"^ lands atop you, knocking you to the ground and impaling you upon a*" special writhe impale give
"You impale yourself upon the deadly tip of a crystal glaive, wedged securely in" special writhe impale give
"A glowing spear comes flying in towards you. It buries itself in your gut,*" special writhe impale give 
"Your health drains further as your body painfully twitches on the soulspear." special writhe impale give
"before whipping the tip around and impaling you upon it." special writhe impale give
"You are impaled and must writhe off before you may do that." special writhe impale give
"You begin to writhe helplessly, the weapon impaling you limiting your movement." special writhe impale give
"You slam into ^ braced * with a scream of pain." special writhe impale give
"With a vicious snarl ^ carves a merciless swathe through your steaming guts." special writhe impale cure

# Ropes.
"You have writhed free of your entanglement by ropes." special writhe ropes cure
"You have writhed free of your entanglement by tied ropes." special writhe ropes cure
"You have been bound by invisible ropes!" special writhe ropes give
"A pair of vines suddenly lashes out from the undergrowth to entangle you!" special writhe ropes give
"A thin net trails the arrow, entangling you as it strikes." special writhe ropes give
"A net arrow strikes you in the *." special writhe ropes give
"^ hurls a tarot card with the image of the Hanged Man on it at you.*" special writhe ropes give
"Your legs are tangled in a mass of rope and you cannot move." special writhe ropes give
"You are too tangled up to do that." special writhe ropes give
"You are bound and cannot do that." special writhe ropes give
"You spring a trap!! A loop of rope entwines around you, pulling you off your*" special writhe ropes give
"A pair of vines suddenly lashes out from the undergrowth to entangle you!" special writhe ropes give
"You begin to struggle free of your entanglement." special writhe ropes begin
"*you squeezing tightly as the air escapes your lungs." special writhe ropes give
"You gasp and choke as *your entanglement impedes your breathing." special writhe ropes give
"A ssylsin hunter casts a large rope net over you, binding your body." special writhe ropes give

# Arrow.
"You begin to trying to break free from the arrow." special writhe arrow begin
"You have broken free from the arrow." special writhe arrow cure
"The arrow spears into you, pinning you to the ground." special writhe arrow give
"You are pinned to the ground by an arrow." special writhe arrow give

# Dart.
"You have escaped from the dart." special writhe dart cure
"^ whips ^ arm downwards and looses a long dart, piercing your body*" special writhe dart give
"You struggle to escape the dart pinning you to the ground." special writhe dart begin

# Net.
"You struggle to escape from the entangling net." special writhe net begin
"You finally free yourself from the net." special writhe net cure
"A goblin hunter flings a large net at you, entangling your limbs." special writhe net give
"A massive net flies in from the ^, entangles itself about you and you*" special writhe net give

# Strangle.
"You begin to struggle against the haft of the weapon that's choking you." special writhe strangle begin
"You have successful wrenched your neck free of the grip that was choking*" special writhe strangle cure
"^ quickly wraps the haft of a truesilver glaive around your*" special writhe strangle give
"You are being strangled and must first writhe free of your captor." special writhe strangle give

# Bolts.
"You struggle against the massive bolt which has impaled you." special writhe bolt begin
"You pull the bolt from your chest, freeing yourself from it." special writhe bolt cure
"The bolt slams into the ground, pinning you beneath it." special writhe bolt give
"You are impaled to the ground by a massive bolt." special writhe bolt give


# Pull Arrows.
"You howl in pain as a barbed arrow pierces your flesh." special arrows add
"Sparks catch your eye as an arrow cuts through the air, buryi*" special arrows add
"You manage to pull the buried arrowhead from your body with intense*" special arrows remove
"You shudder in pain as you wrench the bloody arrow from your flesh." special arrows remove
"There is not an arrow in your body to remove." special arrows clear


# Limb breaks.  We DO have illusion problems...  Level 2 suggested.
# Level 3 - Level 2 mangled limb. (2rest, mend)
"To your horror, your * has been mutilated beyond repair by ordinary " special part any mangled2 X !F
# Level 2 - Level 1 mangled limb. (rest, mend)
"Your * is greatly damaged from the beating." special part any mangled X !F
"Your * is greatly healed, but still damaged." special part any mangled
"Your right leg is suddenly mangled nearly beyond repair, and pain erupts up*" special part rightleg mangled
"Your right arm is suddenly mangled nearly beyond repair, and pain erupts up*" special part rightarm mangled
"Your left leg is suddenly mangled nearly beyond repair, and pain erupts up*" special part leftleg mangled
"Your left arm is suddenly mangled nearly beyond repair, and pain erupts up*" special part leftarm mangled
"Blue lightning crackles in ^'s eyes and streaks out to your *" special part any mangled
# Level 1 - Crippled limb. (mend)
"Your * feels stronger and healthier." special part any crippled
"Your * snaps in two." special part any crippled
"Rotting arms claw at you from the ground, shrivelling your *" special part any crippled
"You watch, in horror, as your left arm shrivels up*" special part leftarm crippled
"You watch, in horror, as your right arm shrivels up*" special part rightarm crippled
"You watch, in horror, as your left leg shrivels up*" special part rightarm crippled
"You watch, in horror, as your right leg shrivels up*" special part rightarm crippled
"You stumble in terror as your * shrivels into a useless stump." special part any crippled
"The stings paralyse your *." special part any crippled
"You watch with your mouth gaping in horror as your * shrivels up and " special part any crippled
"down painfully to the bone.*" special part oneleg crippled
"You cry out in pain as your * twists and snaps beneath you." special part any crippled
"^ utters a prayer and smites your *." special part any crippled
"Hobbling, you move away to the ^." special part oneleg crippled
"causing massive rocks and boulders to fall down on you." special part oneleg crippled
# Healed limbs.
"Your * becomes functional as the bones quickly mend." special part any healed
"The salve makes your legs feel healthier than they have in years." special part leftleg healed
"The salve makes your legs feel healthier than they have in years." special part rightleg healed
"The salve makes your arms feel healthier than they have in years." special part leftarm healed
"The salve makes your arms feel healthier than they have in years." special part rightarm healed
"The salve makes your * feel healthier than it has in years." special part any healed

# Head damage.
"The massive trauma to your head has damaged your skull and brain considerably." special part head mangled
"Your head is greatly healed, but still damaged." special part head crippled
"You suddenly find it hard to finish thinking of..." special part head crippled
"Your head feels stronger and healthier." special part head healed
"The salve makes your head feel healthier than it has in years." special part head healed
# Torso damage, still in research.
"Your body feels stronger and healthier." special part torso healed

# Unknown leg/arm damage.
"* grabs at your leg, causing it to fail as it shrivels beneath away." special part leg crippled
"^'s strokes your * and it withers away." special part any crippled
"* thrusts ^ blade into your leg, causing it to give way to the pain." special part leg crippled
"The crone strokes your *, withering it into uselessness." special part any crippled
"causing massive rocks and boulders to fall down on you." special part leg crippled
"*shattering a limb." special part leg crippled

# Big ugly one.
"your * and ^ ^ shrivel up in response." special part any crippled
"your ^ ^ and * shrivel up in response." special part any crippled
"Immediately, your * and ^ ^ shrivel up in response." special part any crippled
"Immediately, your ^ ^ and * shrivel up in response." special part any crippled


# "reaches out and grabs your leg, which almost gives way"
# "touches your left arm, and it shrivels away to"
"* touches your left leg, and it shrivels away." special part leftleg crippled
"* touches your right leg, and it shrivels away." special part leftleg crippled

# More legs/arms.
"Wrenching pain shoots through your arms as they are twisted and broken*" special part leftarm crippled
"Wrenching pain shoots through your arms as they are twisted and broken*" special part rightarm crippled
"As all four of your limbs break, pain overwhelms you and you wonder you've*" special part leftarm crippled
"As all four of your limbs break, pain overwhelms you and you wonder you've*" special part rightarm crippled
"As all four of your limbs break, pain overwhelms you and you wonder you've*" special part leftleg crippled
"As all four of your limbs break, pain overwhelms you and you wonder you've*" special part rightleg crippled
"Blue light crackles forth from ^'s palms, striking you down*" special part leftleg crippled
"Blue light crackles forth from ^'s palms, striking you down*" special part rightleg crippled
"Blue light crackles forth from ^'s palms, striking you down*" special part leftarm crippled
"Blue light crackles forth from ^'s palms, striking you down*" special part rightarm crippled
"The Ocean Abomination, Yasyolon breaks into a frenzy, lashing out at *" special part leftleg crippled
"The Ocean Abomination, Yasyolon breaks into a frenzy, lashing out at *" special part rightleg crippled
"The Ocean Abomination, Yasyolon breaks into a frenzy, lashing out at *" special part leftarm crippled
"The Ocean Abomination, Yasyolon breaks into a frenzy, lashing out at *" special part rightarm crippled
"Your legs snap and break beneath you." special part leftleg crippled
"Your legs snap and break beneath you." special part rightleg crippled
"A sudden pain shoots through both your arms and you feel their bones crumble." special part leftarm crippled
"A sudden pain shoots through both your arms and you feel their bones crumble." special part rightarm crippled
"You scream in agony as both your legs break in a horrendous crunch as you land." special part leftleg crippled
"You scream in agony as both your legs break in a horrendous crunch as you land." special part rightleg crippled

# These will happen if we don't know about it.
"Both of your legs must be free and unhindered to do that." special part oneleg crippled
"Your only working arm is off-balance." special part onearm crippled
"As both your arms are crippled, you cannot do that." special part leftarm crippled
"As both your arms are crippled, you cannot do that." special part rightarm crippled
"Your legs are crippled, how will you move?" special part leftleg crippled
"Your legs are crippled, how will you move?" special part rightleg crippled

# These might reset from mangled to crippled, I don't want that.
#"As both your arms are crippled, you cannot do that." special part leftarm crippled
#"As both your arms are crippled, you cannot do that." special part rightarm crippled
#"Both of your legs must be free and unhindered to do that." special part leftleg crippled
#"Both of your legs must be free and unhindered to do that." special part rightleg crippled

#" utters a prayer and smites your %1 %2.$It breaks with a loud 'CRACK'."
#"Before you can avoid it*"


# Misc.
"You have been slain by *." all cure X L 3
"You have been victorious and leave the Arena in triumph!" all cure
"You see a bright light shine on you as all your afflictions are cured." all cure
"You choke as you inhale water." none X L 3 A "eat pear"
"^ makes a sudden, quick gesture in front of you*" none X L 1 A "def"
"Your mana has been fully drained." none X L 1 A "def"
"^ waggles ^ fingers in front of a Vodun doll of *" special ignorenext

# Some useful warnings.
"*circle, gaining speed as he goes." special instakill
"*circle, gaining speed as she goes." special instakill
"* You have only moments left to escape before you are judged!" special instakill
"*bears down on you." special instakill
"With a daegger in hand, * begins to close in on you." special instakill
"The blade on the daegger splits into a semblance of teeth as *" special instakill
"* angel, and it begins to glare piercingly at you." special instakill
"You catch the faint tones of a mournful melody, as though it is coming from *" special instakill
"A look of concentration followed by a look of disgust passes across*" special instakill
"* casts a piercing glance at you." special instakill
"You are suddenly hoisted from your feet by *" special instakill
"You kick and struggle as the life is slowly squeezed out of you." special instakill
#"Panic overcomes you as *" special instakill
"you are almost overcome with panic." special instakill A "pull arrow from body"
"silence overtakes your surroundings." special instakill
"silence overtakes your surroundings." special instakill
"silence overtakes your surroundings." special instakill
"^ holds ^ mouth open, a word of power continously emanating*" special instakill
"^ projects the single, pure note of ^ voice at you." special instakill

# Mage instakill.
"*chaotic dance through and around ^ body." special instakill
"A jagged bolt of lightning dances off ^'s body, coursing*" special instakill
"Chunks of stone buzz in from every direction to focus in a swirl*" special instakill
"You are struck with a barrage of jagged stone as the swiring slabs*" special instakill
"*about ^ in a hungry rush." special instakill
"The flames surrounding ^ suddenly wink out, reappearing*" special instakill
"^ directs a frosty stare in your direction as ^ strains*" special instakill
"Warmth returns to * skin as the cloud of ice passes to you." special instakill

# A good idea would be to hold our breath, when noosed.
"You are suddenly hoisted from your feet by *" none X L 1 A "hold breath"

# Maybe we were the target, check it. Twice, because concussion gives amnesia.
"^ flicks the temple of a doll of ^, hard." none X L 2 A "diag"
"^ flicks the temple of a doll of ^, hard." none X L 2 A "diag"

# Batter. Stupidity, Epilepsy and Dizziness, all at once.
"You reel as your mind is viciously battered by a mental assault from *" stupidity give
"You reel as your mind is viciously battered by a mental assault from *" epilepsy give
"You reel as your mind is viciously battered by a mental assault from *" dizziness give


# New Idras afflictions.

# Equilibrium-slow
"You suddenly find it hard to focus your senses." equilibrium-slow give
"You are able to focus your senses once more." equilibrium-slow cure

# Balance-slow
"Motion trails appear before your eyes, and your ability to balance seems off." balance-slow give
"You are able to focus your senses once more." balance-slow cure


# Herbs-reject
#"You feel a noticeable change in your body's internal chemistry." herbs-reject give
"A cold sweat overtakes you, your skin suddenly turning pale and clammy." herbs-reject give
"You feel * absorbed into your body with no effect." herbs-reject give
"Your skin warms, restoring health and vitality." herbs-reject cure

# Herbs-slow
"A faintness takes you as your stomach begins to grumble ceaselessly." herbs-slow give
"Your stomach ceases grumbling." herbs-slow cure

# Salve-slow
"You begin sweating heavily, your skin heating to unnatural temperatures." salves-slow give
"Your sweating subsides and your skin temperature returns to normal." salves-slow cure

# Elixirs-slow
"Your ability to digest elixirs seems off for some reason." elixirs-slow give
"Your ability to digest elixirs stabilizes." elixirs-slow cure

# Bardic Yoth. Drink something, to make sure it wasn't an illusion.
"You clutch your throat as it shrivels, allowing nothing to pass." special yoth give X A "drink immunity"
"You cannot eat anything in such a state!" special yoth give
"You cannot drink anything in such a state!" special yoth give
"You take a drink from *" special yoth cure X S
"You feel your throat unclench and return to normal." special yoth cure

# Withered-throat.
"Panic temporarily takes you as your throat closes up." withered-throat give
"You feel your throat tighten." withered-throat give
"restricted airway." withered-throat give X !F
"Your throat is restored as the withering fades." withered-throat cure

# Something. Random affliction.
"The bubonis entity whispers words of madness into your ear*" something give
"^ nods gravely at ^ angel, and it begins to glare piercingly at you." something give
"*, your thoughts become jumbled." something give
"The knowledge that you've been cursed floods your mind." something give
"You are confused as to the effects of the toxin." something give
"You are bedazzled by the sight of a huge gossamer butterfly fluttering wildly." something give
"^ flings a tarot card at you which turns an ominous, sickly red*" something give
"^ lowers ^ eyes and an unholy image appears before you. Unable*" something give
"^ chants something wretched. Unable to bear the images these*" something give
"^ points a ring of pestilence at you." something give
"You feel a wave of sickness wash over you." something give
"^ launches upwards into a swift backflip, catching you under the*" something give
"Your spirit writhes in torment under the glare of the angel." something give
"The strike to your head leaves you dazed." something give
"You are dumbfounded as a small sparrow flutters wildly around you." something give
"You feel sickened and weak by the aura of death emanating from*" something give X A "focus"

# Bandit triggers.
"Netting falls around you and roughly pulls you to the ground, as a group of*" special writhe ropes give X L 1 A "writhe"
"Netting falls around you and roughly pulls you to the ground, as a group of*" special trip
"You stumble as your * shrivels into a useless appendage." special part any crippled
"You watch, in horror, as your * shrivels up and becomes useless." special part any crippled
"catching your legs and tripping you to the ground." special trip
"A prickly stinging overcomes your body, fading away into numbness." paralysis give



# Defence Table.

# Syntax: D defence "name" [X <defext>]
# Where <defext> can be:
#  needy - it needs balance and equilibrium.
#  standing - must not be prone.
#  need* - it needs herb/pipe/salve balance.
#  take* - it also uses the balance.
#  takebalance - it takes balance or equilibrium.
#  A "action" - text to send. If not, then send its name.
#  L <nr> - trigger level needed, to send an action.

# Defences.
#D defence "blindness" X needherb takeherb A "eat hyssop" L 3
#D defence "deafness" X needherb takeherb A "eat juniper" L 3
D defence "blindness" X A "blind" notimer
D defence "deafness" X A "deaf" notimer
D defence "breakfall" X needy standing
D defence "weathering" X
D defence "toughness" X
D defence "vitality" X needy takebalance L 2
D defence "cloak" X needy takebalance A "touch cloak" L 3
#D defence "third eye" X needherb A "eat primrose" L 3
D defence "third eye" X A "thirdeye" L 1
D defence "heightened speed" X A "drink speed" L 3 notimer
D defence "regeneration" X A "regeneration on"
#D defence "insomnia" X needherb A "eat violet" L 3
D defence "insomnia" X L 2
D defence "owl" X takebalance A "touch owl" L 3
D defence "quince" X needherb A "eat quince" L 3
D defence "fenugreek" X A "apply fenugreek" L 3 notimer
D defence "density" X needsalve takesalve A "apply mass" L 3
D defence "mindseye" X needy takebalance A "touch mindseye" L 3
D defence "levitating" X A "drink levitation" L 3
D defence "venom" X A "drink venom" L 3
D defence "temperance" X A "drink frost" L 3
D defence "caloric salve" X A "apply caloric" L 3
D defence "mindnet" X A "mindnet on"
D defence "mind telesense"
D defence "pear" X A "eat pear" L 3
D defence "anti-weapon field" X needsmoke takesmoke A "smoke pipe with linseed" L 3 notimer
D defence "flexibility"
D defence "gripping" X A "grip"
D defence "selfishness" X needy takebalance L 2
D defence "body block" X needy takebalance A "bdb"
D defence "evading" X needy takebalance A "evb"
D defence "pinch block" X needy takebalance A "pnb"
D defence "deathsight" X takebalance needy L 2
D defence "splitting" X needy takebalance A "split mind" L 1
D defence "fitness" X needy takebalance L 2
D defence "resistance" X
D defence "treewatch" X A "treewatch on"
D defence "skywatch" X A "skywatch on"
D defence "vigilance" X A "vigilance on"
D defence "projectiles" X A "projectiles on"
D defence "constitution" X needy takebalance L 2
D defence "consciousness" X A "consciousness on" L 2
D defence "nightsight"
D defence "immunity" X needy takebalance L 2
D defence "breathing" X needy A "hold breath" L 2
D defence "hypersense" X A "hypersense on"
D defence "dodging" X A "dodging on"
D defence "trance" X A "kai trance" notimer
D defence "curseward" X needy takebalance notimer L 2
D defence "celerity" X needy takebalance L 3
D defence "camouflage" X needy L 2
D defence "mimicry" X needy takebalance A "mimic tauraith"
D defence "torch" X needy takebalance A "touch torch" L 3
D defence "elusive" X needy takebalance A "elusiveness on" 
D defence "warning" X needy takebalance
D defence "secure wield" X needy A "secure wielded" L 3
D defence "alertness" X needy takebalance A "alertness on" L 3
D defence "cover tracks" X needy takebalance L 3
D defence "lifesense" X needy takebalance A "lifesence on" L 2
D defence "conceal weapons" X needy L 2
D defence "contort" X needy takebalance L 3



# Defence triggers.

# Blindness.
"You are blind." special defence blindness give X C
"You open your eyes once more, and the world about you is darkness." special defence blindness give
"Your sight fades and you can see no more." special defence blindness give
"You are blind and the hyssop stem has no effect." special defence blindness give
"You can see once more." special defence blindness take
"You pass through a lightwall and with a flash your blindness is cured." special defence blindness take
"^ weaves an intricate dance in an attempt to transfix you, but only*" special defence blindness take
"The Song of Revelation strips you of your blindness and deafness defences*" special defence blindness take
"You blink and sight is with you once more." special defence blindness take
"You can see once more." special defence blindness take
"*attempts to transfix you, but succeeds only in curing your blindness." special defence blindness take
"Your vision and hearing are suddenly restored." special defence blindness take
"Your blindness is cured by a wunjo rune on a totem." special defence blindness take

# Deafness.
"You are deaf." special defence deafness give X C
"Your hearing disappears!" special defence deafness give
"Being deaf, the juniper berry has no effect." special defence deafness give
"The world about you falls silent as the deafness trance sinks upon you." special defence deafness give
"You snap your fingers and instantly you hear again." special defence deafness take
"Silence engulfs you as your hearing fades." special defence deafness give
"Your hearing has returned." special defence deafness take
"Your hearing is suddenly restored*" special defence deafness take
"Your vision and hearing are suddenly restored." special defence deafness take
"Your hearing has returned." special defence deafness take
"Your deafness renders you immune to the battlecry, but your hearing suddenly*" special defence deafness take
"You fall to your knees and clutch your ears as the terrifying shaft of sound*" special defence deafness take

# Insomnia.
"You have insomnia, and cannot easily go to sleep." special defence insomnia give X C
"Focusing your mind you banish all possibility of sleep." special defence insomnia give
"You suddenly feel incapable of falling asleep." special defence insomnia give
"You are already an insomniac." special defence insomnia give X S
"Your insomnia has cleared up." special defence insomnia take X C
"Your insomnia has been cured by the mandrake." special defence insomnia take
"Your mind relaxes and you feel as if you could sleep." special defence insomnia take
"The song strips away your insomnia defence." special defence insomnia take
"You open your eyes and yawn mightily." special defence insomnia take X S
"You are jerked awake by the pain." special defence insomnia take X S
"You quickly pull yourself out of sleep." special defence insomnia take X S

# Quince.
"You have eaten the quince fruit and are extremely energetic." special defence quince give X C
"A feeling of energy and excitement overcomes you." special defence quince give
"The song strips away your quince defence." special defence quince take
"You feel yourself calm down as the quince nut wears off*" special defence quince take
"You begin your struggle to escape from the dreamworld." special defence quince take X S

# Anti-weapon field.
"You are protected from hand-held weapons with an aura of rebounding." special defence "anti-weapon field" give X C
"You feel an aura of rebounding surround you." special defence "anti-weapon field" give
"Your aura of weapons rebounding disappears." special defence "anti-weapon field" take
"^ razes your aura of rebounding with a*" special defence "anti-weapon field" take

# Caloric salve.
"You are protected from the freezing elements." special defence "caloric salve" give X C
"A feeling of comfortable warmth spreads over you." special defence "caloric salve" give
"You concentrate for a moment and a feeling of comfortable warmth fills you." special defence "caloric salve" give
"Your body warms up and you stop shivering." special defence "caloric salve" take X S
"Your caloric salve dissolves as it ameliorates the extreme cold." special defence "caloric salve" take

# Density (Mass).
"You are extremely heavy and difficult to move." special defence density give X C
"Your body grows extremely dense and heavy as the mass salve infuses your skin." special defence density give
"You feel your density return to normal." special defence density take

# Heightened Speed.
"Your sense of time is heightened, and your reactions are speeded." special defence "heightened speed" give X C
"Tiny tremours spread through your body as the world seems to slow down." special defence "heightened speed" give
"* blows an Aeon tarot at you, destroying your speed defence." special defence "heightened speed" take
"You feel your passage through time slow." special defence "heightened speed" take
"Your speed defence is destroyed by an unseen force." special defence "heightened speed" take X A "apply restoration to head"
"Your speed defence is destroyed by an unseen force." none X A "apply restoration to head"
"Your speed defence is destroyed by an unseen force." none X A "drink speed"

# Fenugreek.
"You are protected by a waxy coating." special defence fenugreek give X C
"The fenugreek berry juice hardens into a supple, waxy coating." special defence fenugreek give
"* flays your fenugreek protection." special defence fenugreek take

# Temperance (Frost).
"You are tempered against fire damage." special defence temperance give X C
"A chill runs over your icy skin." special defence temperance give

# Venom.
"Your resistance to damage by poison has been increased." special defence venom give X C
"You feel a momentary dizziness as your resistance to damage by poison*" special defence venom give

# Levitation.
"You are walking on a small cushion of air." special defence levitating give X C
"Your body begins to feel lighter and you feel that you are floating slightly." special defence levitating give

# Pear.
"form an air pocket around you." special defence pear give
"The bubble of air around you dissipates." special defence pear take
"The pocket of air around you dissipates into the atmosphere." special defence pear take

# Deathsight.
"Your mind has been touched by Thanatos, God of Death." special defence deathsight give X C
"God of Death, form in your mind." special defence deathsight give
"later, you feel inextricably linked with Death itself." special defence deathsight give
"Your mind is already touched by the God of Death." special defence deathsight give
"You are no longer attuned to the Underworld." special defence deathsight take

# Selfishness.
"You are feeling quite selfish." special defence selfishness give X C
"You rub your hands together greedily." special defence selfishness give
"You already are a selfish bastard." special defence selfishness give X S
"A feeling of generosity spreads throughout you." special defence selfishness take
"No worries. You're not a selfish bastard as is." special defence selfishness take

# Curseward.
"A curseward has been established about your person." special defence curseward give X C
"Your curseward is complete." special defence curseward give

# Third eye.
"You can perceive the unobvious through the sense of your thirdeye." special defence "third eye" give X C
"You now possess the gift of the third eye." special defence "third eye" give
"You already possess the third eye." special defence "third eye" give X S

# Breakfall.
"You are prepared to fall properly." special defence breakfall give X C
"You prepare yourself to fall properly." special defence breakfall give
"With incredible skill you tumble the ground, taking no damage." special defence breakfall take X C

# Weathering.
"Your body is weathering the storm of life a little better." special defence weathering give X C
"A brief shiver runs through your body." special defence weathering give

# Toughness.
"Your skin is toughened." special defence toughness give X C
"surface of your skin." special defence toughness give

# Regeneration.
"You are regenerating lost health through the power of Kaido." special defence regeneration give X C
"You begin to concentrate on regeneration of your wounds." special defence regeneration give
"You call a halt to the regenerative process." special defence regeneration take

# Fitness.
"You are utilising your bodily control to become more fit." special defence fitness give X C
"You inhale deeply, allowing the air to fill your mighty lungs." special defence fitness give
"The effect of the mercury toxin burns away at your fitness." special defence fitness take
"Your fitness is burned off by the effect of the curse." special defence fitness take
"Your fitness is burned off by the effect of the evileye." special defence fitness take
"You need equilibrium to increase your fitness." special defence fitness take
"You must have balance to increase your fitness." special defence fitness take

# Resistance.
"You are resisting magical damage." special defence resistance give X C
"You call aloud and feel an aura of resistance shroud itself silently about you." special defence resistance give

# Constitution.
"You are using your superior constitution to prevent nausea." special defence constitution give X C
"You clench the muscles in your stomach, determined to assert your superior " special defence constitution give

# Consciousness.
"You are maintaining consciousness at all times." special defence consciousness give X C
"You will remain conscious at all times." special defence consciousness give
"You will no longer concentrate on retaining full consciousness." special defence consciousness take

# Projectiles.
"You are alert to incoming projectiles." special defence projectiles give X C
"You look about sharply, poised to avoid all incoming projectiles." special defence projectiles give
"You cease your watch for projectiles." special defence projectiles take
"You cease watching for projectiles." special defence projectiles take

# Dodging.
"You are watching the skies for danger." special defence dodging give X C
"You resolve to keep an eye on the skies for danger." special defence dodging give
"You cease watching the skies." special defence dodging take

# Splitting.
"Your mind is split, allowing constant meditation." special defence splitting give X C
"You begin to devote a portion of your Kaido-trained mind to constant, " special defence splitting give
"You cease the process of Kai meditation, joining the split segments of your " special defence splitting take

# Vitality.
"You will call upon your fortitude in need." special defence vitality give X C
"Your body positively glows with health and vitality." special defence vitality give
"A surge of rejuvenating energy floods your system, healing your wounds." special defence vitality take

# Immunity.
"You close your eyes and grit your teeth, feeling the heat of the blood pumping " special defence immunity give
"You cease concentrating on immunity." special defence immunity take

# Breathing.
"You inhale deeply and begin holding your breath." special defence breathing give
"You cease holding your breath and exhale loudly." special defence breathing take

# Kai Trance.
"You are utilising the trance to store Kai energy." special defence trance give X C
"Your mantra is complete - the Kai Trance is upon you." special defence trance give
"energy vanish." special defence trance take
"Your mana has been fully drained." special defence trance take

# Taekate blocks.
"You will try to pinch block a weakened foe." special defence "pinch block" give X C
"You are using Taekate to evade incoming attacks." special defence evading give X C
"You are trying to absorb blows to your body." special defence "body block" give X C
"You ready yourself to pinch block to the best of your ability." special defence "pinch block" give
"You ready yourself to evade incoming blows." special defence evading give
"You ready yourself to block as best you can." special defence "body block" give
"You drop all your blocks." special defence "body block" take
"You drop all your blocks." special defence "pinch block" take
"You drop all your blocks." special defence evading take

# Mind Telesense (not perception's).
"You are using your telesense." special defence "mind telesense" give X C
"You attune your mind to tampering from telepathy." special defence "mind telesense" give
"You cease to concentrate your mind on mindlock attempts." special defence "mind telesense" take

# Mindnet.
"You have cast a mindnet over the local area." special defence mindnet give X C
"about the surrounding land." special defence mindnet give
"You cease concentration and your mind net vanishes." special defence mindnet take
"Your mana has been fully drained." special defence mindnet take

# Hypersense.
"You are using your hypersense." special defence hypersense give X C
"You begin detecting mindlock attempts in your local area." special defence hypersense give
"You turn hypersense off." special defence hypersense take

# Cloak.
"You are surrounded by a cloak of protection." special defence cloak give X C
"You caress the tattoo and immediately you feel a cloak of protection surround*" special defence cloak give

# Mindseye.
"Your senses are heightened." special defence mindseye give X C
"Touching the mindseye tattoo, your senses are suddenly heightened." special defence mindseye give
"You relax your mindseye." special defence mindseye take

# Owl.
"The aura of the owl surrounds you." special defence owl give X C
"You feel the knowledge of the owl descend upon you as you caress the owl " special defence owl give

# Torch.
"You have activated the torch tattoo." special defence torch give X C
"You feel your skin warm as you activate the torch tattoo." special defence torch give

# Vigilance.
"You are vigilant to attempts to hypnotise you." special defence vigilance give X C
"You are now watching out for attempts to hypnotise you." special defence vigilance give
"You relax your vigilance." special defence vigilance take

# Alertness.
"Your senses are attuned to nearby movement." special defence alertness give X C
"You prick up your ears." special defence alertness give
"You cease your watchful alertness." special defence alertness take

# Treewatch.
"You are watching the trees for signs of movement." special defence treewatch give X C
"You begin to keep a watchful eye on the treeline." special defence treewatch give
"You cease to watch the treeline." special defence treewatch take

# Skywatch.
"You are aware of movement in the skies." special defence skywatch give X C
"You are now watching the skies." special defence skywatch give
"You are no longer watching the skies." special defence skywatch take

# Nightsight.
"Your vision is heightened to see in the dark." special defence nightsight give X C
"Your vision sharpens with light as you gain night sight." special defence nightsight give

# Warning.
"You are carefully watching for prying eyes." special defence warning give X C
"You carefully watch for prying eyes." special defence warning give
"You cease watching for prying eyes." special defence warning take

# Lifesense.
"You are actively searching for life in the land around you." special defence lifesense give X C
"You begin actively searching out the life in the land around you." special defence lifesense give

# Flexibility.
"You are looking a little shady today." special defence flexibility give X C
"You are prepared to escape from enemy bonds." special defence flexibility give

# Gripping.
"Your hands are gripping your wielded items tightly." special defence gripping give X C
"You strengthen your grip until your fists are rock solid." special defence gripping give

# Mimicry.
"You are using an assumed identity." special defence mimicry give X C
"You begin to mimic the looks of *." special defence mimicry give
"You slough off your mimicry and become yourself again." special defence mimicry take

# Camouflage.
"You are covered in camouflage, and many of your actions are hidden." special defence camouflage give X C
"Crushing the fenugreek and wormwood, you mix them together and spread them over*" special defence camouflage give

# Secure wield.
"Your wielded weapons are attached to your wrists by thin strips of leather." special defence "secure wield" give X C
"You wrap thin strips of leather around your wrists and attach it to your *" special defence "secure wield" give

# Conceal weapons.
"You are hiding your weapons underneath your cloak." special defence "conceal weapons" give X C
"You carefully hide your weapons under the folds of your cloak." special defence "conceal weapons" give

# Cover tracks.
"You are covering your tracks to make youself harder to find." special defence "cover tracks" give X C
"You pull your cloak closer around you and begin to pay close attention to *" special defence "cover tracks" give

# Elusive.
"You are alert to those who would pursue you." special defence elusive give X C
"Your eyes flicker this way and that as you watch for pursuers." special defence elusive give
"You cease watching for pursuit." special defence elusive take

# Contort.
"You are ready to contort your body out of that which binds you." special defence contort give X C
"You prepare yourself to contort out of that which binds you." special defencecontort give

# Celerity.
"You are moving with heightened celerity." special defence celerity give X C
"You inhale deeply, filling your lungs with air, preparing for increased*" special defence celerity give
"You relax your celerity defence." special defence celerity take


# Defence strips.
"You suddenly feel that it would be a fine idea to relax your *" special defence any take
"Your * defence is stripped away." special defence any take
"A small brown lemming scurries around you furiously, stripping your *" special defence any take
"Your * defence has been stripped as your body vibrates in sync " special defence any take
"Your * defence has been stripped as your body vibrates in sync with " special defence any take
"The Song of Revelation strips you of your blindness and deafness defences*" special defence deafness take
"^ spins his shield causing you to relax your * defence." special defence any take
"Your * defence has been stripped by ^'s Ouroboros." special defence any take
"Your * defence erodes away." special defence any take
"A snowshoe hare scampers about underfoot, stripping your * defence." special defence any take
"A lithe ferret races beneath your feet, stripping your * defence." special defence any take
"Your * defence has been stripped by ^'s holy seraph." special defence any take
"Your * defence has been stripped as your body vibrates in sync with a " special defence any take
#"* defence." special defence any take

# Misc.
"Current Defences:" special defence all take X S C
"Password correct. Welcome to Imperian." special defence all take X C S


# End of file.
