#!/bin/sh
# Section: ["section_name"]
# Option:  opt_name numeric_value
# Defence: D "defence_name" on/off
#          D "all" on/off
# Prompt:  P "prompt"

# Options that are above all sections will be always loaded.

clot_mana_usage 5
cure_with_tree 1
cure_with_purge 1
cure_with_focus 0
show_afflictions 1
tree_recovery 10
arti_pipes 0
reset_time 3
can_kipup 0
perma_moss 0

# Sections begin here.

["init"]
level 2
health 250
mana 200
toadstool_heal 0
toadstool_mana 0
kai_heal 0
transmute 150
show_info_on_term 0
use_mana_above 150
D "breakfall" on
D "weathering" on
D "toughness" on
D "deathsight" on
D "fitness" on
D "resistance" on
D "constitution" on
D "consciousness" on
D "selfishness" on
D "insomnia" on
D "third eye" on
D "warning" on
D "splitting" once
D "regeneration" on
# Huge, I know, but nice.
P "^x<^1%h^x/^g%H^xh ^2%m^x/^g%M^xm ^3%e^xe ^4%w^xw ^g%x^xx ?k{^5%k^xk }<?e{^ge^x}!{-}?b{^gb^x}!{-}?l{^gp^x}!{-}?r{^gp^x}!{-}>?A{ <^r}?H{h}?S{s}?P{p}?C{c}?T{t}?F{f}?U{b}?W{w}?A{^x>}?a{ <^Y}?p{p}?f{f}?B{b}?d{d}?s{s}?t{^b%t^Y}?L{^Gl^Y}?M{^Rl^Y}?a{^x>}?D{ <^r%D^x>}>^x "
# Non monk prompt.
#P "^x<^1%h^x/^g%H^xh ^2%m^x/^g%M^xm ^3%e^xe ^4%w^xw^x <?e{^ge^x}!{-}?b{^gb^x}!{-}>?A{ <^r}?H{h}?S{s}?P{p}?C{c}?T{t}?F{f}?U{b}?W{w}?A{^x>}?a{ <^Y}?p{p}?f{f}?B{b}?d{d}?s{s}?t{^b%t^Y}?a{^x>}?D{ <^r%D^x>}>^x "

["aetolia_init"]
P "^R<^x^1%h^x/^g%H^xh ^2%m^x/^g%M^xm ^3%e^xe ^4%w^xw ^g%x^xx <?e{^ge^x}!{-}?b{^gb^x}!{-}>?A{ <^r}?H{h}?S{s}?P{p}?C{c}?W{w}?A{^x>}?a{ <^Y}?p{p}?f{f}?B{b}?d{d}?s{s}?c{c}?a{^x>}?D{ <^r%D^x>}^R>^x "


["none"]
D all off

["combat"]
level 3
health 250
mana 150
toadstool_heal 150
kai_heal 150
transmute 200
keep_standing 1
double_actions 1
show_info_on_term 1
keep_pipes_lit 1
outr_once 0

["passive"]
level 2
health 100
mana 150
toadstool_heal 0
toadstool_mana 0
kai_heal 0
transmute 100
use_mana_above 150
keep_standing 0
double_actions 0
show_info_on_term 0
keep_pipes_lit 0
outr_once 0
D all off
D "breakfall" on
D "weathering" on
D "toughness" on
D "deathsight" on
D "fitness" on
D "resistance" on
D "constitution" on
D "consciousness" on
D "selfishness" on
D "insomnia" on
D "third eye" on

# Mostly used for arena. Even though `kall works just well too.
["defences"]
D "heightened speed" on
D "insomnia" on
D "quince" on
D "fenugreek" on
D "levitating" on
D "temperance" on
D "caloric salve" on
D "trance" on

["arena"]
level 3
health 250
mana 150
toadstool_heal 260
toadstool_mana 250
kai_heal 150
transmute 200
keep_standing 1
double_actions 1
show_info_on_term 1
keep_pipes_lit 1
outr_once 1
D "heightened speed" on
D "insomnia" on
D "quince" on
D "fenugreek" on
D "levitating" on
D "temperance" on
D "caloric salve" on
D "trance" on

# End of file.
